Repository denysdovhan/vacuum-card, pull requests merged in 2020-12, with the labels that each got.

#149 Update README.md
  README.md
Labels: documentation

#151 Added segment cleaning in german translation
  src/translations/de.json
Labels: documentation

#156 Added "segment cleaning" in spanish translation
  src/translations/es.json
Labels: enhancement

#157 Added Roborock S6 MaxV to supported models list
  README.md
Labels: documentation

#134 Address crash in `map` when using compact view
  src/vacuum-card.js
Labels: bug
