Repository denysdovhan/vacuum-card, pull requests merged in 2020-05, with the labels that each got.

#3 fix typo in README.md
  README.md
Labels: documentation

#9 Update README.md
  README.md
Labels: documentation

#13 Various improvements/fixes for v1
  src/vacuum-card.js
Labels: bug

#15 Don't try to render source if vacuum doesn't support it
  src/vacuum-card.js
Labels: bug

#19 Update README.md
  README.md
Labels: documentation

#28 Adding Roomba 960
  README.md
Labels: documentation

#30 Adding Xiaomi Mi Robot 1S
  README.md
Labels: documentation

#29 add configurable per state stats
  README.md
  src/vacuum-card.js
Labels: enhancement

#37 typos
  README.md
Labels: documentation

#34 Adding dutch translation
  src/translations/nl.json
Labels: enhancement

#40 Added nl to localization
  src/localize.js
Labels: enhancement

#43 Add French translations
  src/localize.js
  src/translations/fr.json
Labels: enhancement

#51 Add Roborock E25 to list of supported vacuums
  README.md
Labels: documentation

#53 Added russian translation
  src/localize.js
  src/translations/ru.json
Labels: enhancement

#50 Added italian translation.
  src/localize.js
  src/translations/it.json
Labels: enhancement

#55 Correction in polish translation
  src/translations/pl.json
Labels: enhancement

#59 0.110.0 Icon Fix
  src/styles.js
  src/vacuum-card.js
Labels: enhancement

#61 Browser Language Fallback
  src/localize.js
Labels: enhancement

#62 Source Localization
  src/translations/en.json
  src/vacuum-card.js
Labels: enhancement

#58 Added Spanish translation
  README.md
  src/localize.js
  src/translations/es.json
Labels: enhancement

#72 Update README.md
  README.md
Labels: documentation
