Repository denysdovhan/vacuum-card, pull requests merged in 2021-02, with the labels that each got.

#163 add Supported models Mijia Robot Vacuum Cleaner 1C
  README.md
Labels: documentation

#178 Update README.md
  README.md
Labels: documentation

#177 Update README.md
  README.md
Labels: documentation

#174 Add supported device Roborock S6 Pure
  README.md
Labels: documentation

#172 Update README.md
  README.md
Labels: documentation

#166 Fallback to entity.state for status and lowercase all translation keys
  README.md
  src/localize.js
  src/translations/cs.json
  src/translations/da.json
  src/translations/de.json
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  src/translations/he.json
  src/translations/hu.json
  src/translations/it.json
  src/translations/ko.json
  src/translations/nb.json
  src/translations/nl.json
  src/translations/pl.json
  src/translations/pt.json
  src/translations/ru.json
  src/translations/sv.json
  src/translations/uk.json
  src/vacuum-card.js
Labels: bug, enhancement

#135 Support for nested attributes in stats
  package-lock.json
  package.json
  src/vacuum-card.js
Labels: enhancement

#180 Update es.json
  src/translations/es.json
Labels: bug

#182 Update locate icon to be aligned with vacuum card
  src/vacuum-card.js
Labels: bug

#173 Added finnish translation
  README.md
  src/localize.js
  src/translations/fi.json
Labels: enhancement

#186 Update es.json
  src/translations/es.json
Labels: bug

#185 Add Robovac 30c to suppoorted vacuums list
  README.md
Labels: documentation
