Repository denysdovhan/vacuum-card, pull requests merged in 2021-11, with the labels that each got.

#273 Update README.md
  README.md
Labels: documentation

#274 Update README.md
  README.md
Labels: documentation

#277 Update README.md
  README.md
Labels: documentation

#270 Update README.md
  README.md
Labels: documentation

#258 Add pt.json in localize.json
  src/localize.js
Labels: enhancement

#264 Updated Ukrainian translation
  src/translations/uk.json
Labels: enhancement

#265 FIX HE translation
  src/translations/he.json
Labels: enhancement

#183 Default button actions overrides
  README.md
  src/localize.js
  src/translations/cs.json
  src/translations/da.json
  src/translations/de.json
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  src/translations/he.json
  src/translations/hu.json
  src/translations/it.json
  src/translations/ko.json
  src/translations/nb.json
  src/translations/nl.json
  src/translations/pl.json
  src/translations/pt.json
  src/translations/ro.json
  src/translations/ru.json
  src/translations/sv.json
  src/translations/uk.json
  src/vacuum-card.js
Labels: enhancement

#271 New translations added.
  src/translations/en.json
  src/translations/es.json
Labels: enhancement

#283 Update de.json
  src/translations/de.json
Labels: bug

#285 Update Russian translation.json
  src/translations/ru.json
Labels: enhancement
